/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.coracaopet;

import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.*;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author USER
 */
public class HomeUser extends javax.swing.JFrame {

    /**
     * Creates new form homeuser
     * @param adm
     */
    public HomeUser(Admin adm) {
        initComponents();
        System.out.println(adm.isIsAdmin());
        btVisibilityAdmin(adm);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roundButton = new jbutton6("C:\\Users\\USER\\Downloads\\Rectangle 14 (1).png");
        jLabel4 = new javax.swing.JLabel();
        btOrg = new javax.swing.JButton();
        roundButton1 = new jbutton6("C:\\Users\\USER\\Downloads\\Rectangle 14 (1).png");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coração Pet");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(21, 198, 148));
        jPanel1.setLayout(null);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/asd.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(350, -10, 90, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ADOCAO_1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 120, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/REGISTRODEANIMAIS.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 350, 300, 30);

        roundButton.setPreferredSize(new Dimension(100, 100));
        add(roundButton);
        roundButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crud_de_animais.png"))); // NOI18N
        roundButton.setBorder(null);
        roundButton.setBorderPainted(false);
        roundButton.setContentAreaFilled(false);
        roundButton.setFocusPainted(false);
        roundButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crud_de_animais_shiny.png"))); // NOI18N
        roundButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crud_de_animais_dark.png"))); // NOI18N
        roundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButtonActionPerformed(evt);
            }
        });
        getContentPane().add(roundButton);
        roundButton.setBounds(40, 330, 400, 210);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tituloOrganizacao.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 260, 210, 37);

        btOrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/organizacao.png"))); // NOI18N
        btOrg.setBorderPainted(false);
        btOrg.setContentAreaFilled(false);
        btOrg.setFocusable(false);
        btOrg.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/organizacao_shiny.png"))); // NOI18N
        btOrg.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/organizacao_dark.png"))); // NOI18N
        btOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrgActionPerformed(evt);
            }
        });
        getContentPane().add(btOrg);
        btOrg.setBounds(440, 240, 340, 170);

        roundButton.setPreferredSize(new Dimension(100, 100));
        add(roundButton);
        roundButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BT ADOCAO.png"))); // NOI18N
        roundButton1.setBorder(null);
        roundButton1.setBorderPainted(false);
        roundButton1.setContentAreaFilled(false);
        roundButton1.setFocusPainted(false);
        roundButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BT ADOCAO DARK.png"))); // NOI18N
        roundButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BT ADOCAO SHINY.png"))); // NOI18N
        roundButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(roundButton1);
        roundButton1.setBounds(40, 110, 400, 210);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrgActionPerformed
        // TODO add your handling code here:
        new CrudFuncionarios().setVisible(true);
    }//GEN-LAST:event_btOrgActionPerformed

    private void roundButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton1ActionPerformed
        try {
            // TODO add your handling code here:
            new TelaAdocao().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(HomeUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_roundButton1ActionPerformed

    private void roundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButtonActionPerformed
        // TODO add your handling code here:
        new CrudAnimais().setVisible(true);

    }//GEN-LAST:event_roundButtonActionPerformed

    private void btVisibilityAdmin(Admin adm) {
        System.out.println("Valor de isAdmin na visibilidade: " + adm.isIsAdmin());
        btOrg.setVisible(adm.isIsAdmin());
        jLabel4.setVisible(adm.isIsAdmin());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin adm = new Admin();
                adm.setIsAdmin(true);
                new HomeUser(adm).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOrg;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton roundButton;
    private javax.swing.JButton roundButton1;
    // End of variables declaration//GEN-END:variables
}
