/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.coracaopet;

import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.*;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author USER
 */
public class HomeUser extends javax.swing.JFrame {

    /**
     * Creates new form homeuser
     * @param adm
     */
    public HomeUser(Admin adm) {
        initComponents();
        System.out.println(adm.isIsAdmin());
        btVisibilityAdmin(adm);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homebutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roundButton = new jbutton6("C:\\Users\\USER\\Downloads\\Rectangle 14 (1).png");
        jLabel4 = new javax.swing.JLabel();
        btOrg = new javax.swing.JButton();
        roundButton1 = new jbutton6("C:\\Users\\USER\\Downloads\\Rectangle 14 (1).png");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(21, 198, 148));

        homebutton.setBackground(new java.awt.Color(217, 217, 217));
        homebutton.setFont(new java.awt.Font("Hammersmith One", 0, 11)); // NOI18N
        homebutton.setText("HOME");
        homebutton.setFocusPainted(false);
        homebutton.setPreferredSize(new java.awt.Dimension(80, 25));
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(217, 217, 217));
        jButton1.setFont(new java.awt.Font("Hammersmith One", 0, 11)); // NOI18N
        jButton1.setText("ADOÇÃO");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(217, 217, 217));
        jButton2.setFont(new java.awt.Font("Hammersmith One", 0, 11)); // NOI18N
        jButton2.setText("VACINAS");
        jButton2.setFocusPainted(false);
        jButton2.setPreferredSize(new java.awt.Dimension(80, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addGap(65, 65, 65)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ADOCAO_1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 120, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\REGISTRO DE ANIMAIS.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 350, 300, 30);

        roundButton.setPreferredSize(new Dimension(100, 100));
        add(roundButton);
        roundButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\OneDrive\\Documentos\\NetBeansProjects\\USTJ-A3-2024-2\\src\\main\\resources\\images\\CRUD DE ANIMAIS FEITO.png")); // NOI18N
        roundButton.setBorder(null);
        roundButton.setBorderPainted(false);
        roundButton.setContentAreaFilled(false);
        roundButton.setFocusPainted(false);
        roundButton.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\CRUD DE ANIMAIS SHINY.png")); // NOI18N
        roundButton.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\CRUD DE ANIMAIS DARK.png")); // NOI18N
        roundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButtonActionPerformed(evt);
            }
        });
        getContentPane().add(roundButton);
        roundButton.setBounds(40, 330, 400, 210);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\ORGANIZAÇÃO (1).png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 260, 210, 37);

        btOrg.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\ORGANIZAÇÃO FEITO (1).png")); // NOI18N
        btOrg.setBorderPainted(false);
        btOrg.setContentAreaFilled(false);
        btOrg.setFocusable(false);
        btOrg.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\organização shiny.png")); // NOI18N
        btOrg.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\ORGANIZAÇÃO DARK (1) (1).png")); // NOI18N
        btOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrgActionPerformed(evt);
            }
        });
        getContentPane().add(btOrg);
        btOrg.setBounds(440, 240, 340, 170);

        roundButton.setPreferredSize(new Dimension(100, 100));
        add(roundButton);
        roundButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BT ADOCAO.png"))); // NOI18N
        roundButton1.setBorder(null);
        roundButton1.setBorderPainted(false);
        roundButton1.setContentAreaFilled(false);
        roundButton1.setFocusPainted(false);
        roundButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BT ADOCAO DARK.png"))); // NOI18N
        roundButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BT ADOCAO SHINY.png"))); // NOI18N
        roundButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(roundButton1);
        roundButton1.setBounds(40, 100, 400, 210);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Home");
    }//GEN-LAST:event_homebuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrgActionPerformed
        // TODO add your handling code here:
        new CrudFuncionarios().setVisible(true);
    }//GEN-LAST:event_btOrgActionPerformed

    private void roundButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundButton1ActionPerformed

    private void roundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Adocao");

    }//GEN-LAST:event_roundButtonActionPerformed

    private void btVisibilityAdmin(Admin adm) {
        System.out.println("Valor de isAdmin na visibilidade: " + adm.isIsAdmin());
        btOrg.setVisible(adm.isIsAdmin());
        jLabel4.setVisible(adm.isIsAdmin());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin adm = new Admin();
                adm.setIsAdmin(true);
                new HomeUser(adm).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOrg;
    private javax.swing.JButton homebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton roundButton;
    private javax.swing.JButton roundButton1;
    // End of variables declaration//GEN-END:variables
}
