/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.coracaopet;

/**
 *
 * @author ACER
 */
public class TelaAdocao extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdocao
     */
    public TelaAdocao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filterPane = new RoundPanel();
        btAplicar = new javax.swing.JButton();
        estadosFilter = new javax.swing.JComboBox<>();
        cidadesFilter = new javax.swing.JComboBox<>();
        lojaFilter = new javax.swing.JComboBox<>();
        ongFilter = new javax.swing.JComboBox<>();
        especieFilter = new javax.swing.JComboBox<>();
        idadeFilter = new javax.swing.JComboBox<>();
        porteFilter = new javax.swing.JComboBox<>();
        sexoFilter = new javax.swing.JComboBox<>();
        jPanel3 = new RoundPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(21, 198, 148));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 96));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 96);

        filterPane.setBackground(new java.awt.Color(217, 217, 217));
        filterPane.setLayout(null);

        btAplicar.setBackground(new java.awt.Color(21, 198, 148));
        btAplicar.setFont(new java.awt.Font("Hammersmith One", 0, 11)); // NOI18N
        btAplicar.setForeground(new java.awt.Color(0, 0, 0));
        btAplicar.setText("Aplicar");
        btAplicar.setFocusPainted(false);
        filterPane.add(btAplicar);
        btAplicar.setBounds(40, 250, 68, 24);

        estadosFilter.setBackground(new java.awt.Color(217, 217, 217));
        estadosFilter.setForeground(new java.awt.Color(0, 0, 0));
        estadosFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        estadosFilter.setFocusable(false);
        filterPane.add(estadosFilter);
        estadosFilter.setBounds(7, 10, 140, 24);

        cidadesFilter.setBackground(new java.awt.Color(217, 217, 217));
        cidadesFilter.setForeground(new java.awt.Color(0, 0, 0));
        cidadesFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterPane.add(cidadesFilter);
        cidadesFilter.setBounds(7, 40, 140, 24);

        lojaFilter.setBackground(new java.awt.Color(217, 217, 217));
        lojaFilter.setForeground(new java.awt.Color(0, 0, 0));
        lojaFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterPane.add(lojaFilter);
        lojaFilter.setBounds(7, 70, 140, 24);

        ongFilter.setBackground(new java.awt.Color(217, 217, 217));
        ongFilter.setForeground(new java.awt.Color(0, 0, 0));
        ongFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterPane.add(ongFilter);
        ongFilter.setBounds(7, 100, 140, 24);

        especieFilter.setBackground(new java.awt.Color(217, 217, 217));
        especieFilter.setForeground(new java.awt.Color(0, 0, 0));
        especieFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterPane.add(especieFilter);
        especieFilter.setBounds(7, 130, 140, 24);

        idadeFilter.setBackground(new java.awt.Color(217, 217, 217));
        idadeFilter.setForeground(new java.awt.Color(0, 0, 0));
        idadeFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterPane.add(idadeFilter);
        idadeFilter.setBounds(7, 160, 140, 24);

        porteFilter.setBackground(new java.awt.Color(217, 217, 217));
        porteFilter.setForeground(new java.awt.Color(0, 0, 0));
        porteFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterPane.add(porteFilter);
        porteFilter.setBounds(7, 190, 140, 24);

        sexoFilter.setBackground(new java.awt.Color(217, 217, 217));
        sexoFilter.setForeground(new java.awt.Color(0, 0, 0));
        sexoFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterPane.add(sexoFilter);
        sexoFilter.setBounds(7, 219, 140, 24);

        getContentPane().add(filterPane);
        filterPane.setBounds(10, 140, 150, 280);

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(190, 140, 440, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdocao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAplicar;
    private javax.swing.JComboBox<String> cidadesFilter;
    private javax.swing.JComboBox<String> especieFilter;
    private javax.swing.JComboBox<String> estadosFilter;
    private javax.swing.JPanel filterPane;
    private javax.swing.JComboBox<String> idadeFilter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> lojaFilter;
    private javax.swing.JComboBox<String> ongFilter;
    private javax.swing.JComboBox<String> porteFilter;
    private javax.swing.JComboBox<String> sexoFilter;
    // End of variables declaration//GEN-END:variables
}
