/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.coracaopet;

/**
 *
 * @author ACER
 */
public class TelaAdocao extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdocao
     */
    public TelaAdocao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new RoundPanel();
        estado = new javax.swing.JLabel();
        arrow1 = new javax.swing.JButton();
        cidade = new javax.swing.JLabel();
        loja = new javax.swing.JLabel();
        ong = new javax.swing.JLabel();
        especie = new javax.swing.JLabel();
        idade = new javax.swing.JLabel();
        porte = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        btAplicar = new javax.swing.JButton();
        arrow2 = new javax.swing.JButton();
        arrow3 = new javax.swing.JButton();
        arrow4 = new javax.swing.JButton();
        arrow5 = new javax.swing.JButton();
        arrow6 = new javax.swing.JButton();
        arrow7 = new javax.swing.JButton();
        arrow8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(21, 198, 148));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 96));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 96);

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        estado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        estado.setForeground(new java.awt.Color(0, 0, 0));
        estado.setText("Estado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 0, 0);
        jPanel2.add(estado, gridBagConstraints);

        arrow1.setBackground(new java.awt.Color(217, 217, 217));
        arrow1.setForeground(new java.awt.Color(0, 0, 0));
        arrow1.setText("▼");
        arrow1.setBorder(null);
        arrow1.setBorderPainted(false);
        arrow1.setContentAreaFilled(false);
        arrow1.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        jPanel2.add(arrow1, gridBagConstraints);

        cidade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cidade.setForeground(new java.awt.Color(0, 0, 0));
        cidade.setText("Cidade");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel2.add(cidade, gridBagConstraints);

        loja.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        loja.setForeground(new java.awt.Color(0, 0, 0));
        loja.setText("Loja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel2.add(loja, gridBagConstraints);

        ong.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ong.setForeground(new java.awt.Color(0, 0, 0));
        ong.setText("ONG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel2.add(ong, gridBagConstraints);

        especie.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        especie.setForeground(new java.awt.Color(0, 0, 0));
        especie.setText("Espécie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel2.add(especie, gridBagConstraints);

        idade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        idade.setForeground(new java.awt.Color(0, 0, 0));
        idade.setText("Idade");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel2.add(idade, gridBagConstraints);

        porte.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        porte.setForeground(new java.awt.Color(0, 0, 0));
        porte.setText("Porte");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel2.add(porte, gridBagConstraints);

        sexo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sexo.setForeground(new java.awt.Color(0, 0, 0));
        sexo.setText("Sexo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        jPanel2.add(sexo, gridBagConstraints);

        btAplicar.setBackground(new java.awt.Color(21, 198, 148));
        btAplicar.setFont(new java.awt.Font("Hammersmith One", 0, 11)); // NOI18N
        btAplicar.setForeground(new java.awt.Color(0, 0, 0));
        btAplicar.setText("Aplicar");
        btAplicar.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(btAplicar, gridBagConstraints);

        arrow2.setBackground(new java.awt.Color(217, 217, 217));
        arrow2.setForeground(new java.awt.Color(0, 0, 0));
        arrow2.setText("▼");
        arrow2.setBorder(null);
        arrow2.setBorderPainted(false);
        arrow2.setContentAreaFilled(false);
        arrow2.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        jPanel2.add(arrow2, gridBagConstraints);

        arrow3.setBackground(new java.awt.Color(217, 217, 217));
        arrow3.setForeground(new java.awt.Color(0, 0, 0));
        arrow3.setText("▼");
        arrow3.setBorder(null);
        arrow3.setBorderPainted(false);
        arrow3.setContentAreaFilled(false);
        arrow3.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        jPanel2.add(arrow3, gridBagConstraints);

        arrow4.setBackground(new java.awt.Color(217, 217, 217));
        arrow4.setForeground(new java.awt.Color(0, 0, 0));
        arrow4.setText("▼");
        arrow4.setBorder(null);
        arrow4.setBorderPainted(false);
        arrow4.setContentAreaFilled(false);
        arrow4.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        jPanel2.add(arrow4, gridBagConstraints);

        arrow5.setBackground(new java.awt.Color(217, 217, 217));
        arrow5.setForeground(new java.awt.Color(0, 0, 0));
        arrow5.setText("▼");
        arrow5.setBorder(null);
        arrow5.setBorderPainted(false);
        arrow5.setContentAreaFilled(false);
        arrow5.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        jPanel2.add(arrow5, gridBagConstraints);

        arrow6.setBackground(new java.awt.Color(217, 217, 217));
        arrow6.setForeground(new java.awt.Color(0, 0, 0));
        arrow6.setText("▼");
        arrow6.setBorder(null);
        arrow6.setBorderPainted(false);
        arrow6.setContentAreaFilled(false);
        arrow6.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        jPanel2.add(arrow6, gridBagConstraints);

        arrow7.setBackground(new java.awt.Color(217, 217, 217));
        arrow7.setForeground(new java.awt.Color(0, 0, 0));
        arrow7.setText("▼");
        arrow7.setBorder(null);
        arrow7.setBorderPainted(false);
        arrow7.setContentAreaFilled(false);
        arrow7.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        jPanel2.add(arrow7, gridBagConstraints);

        arrow8.setBackground(new java.awt.Color(217, 217, 217));
        arrow8.setForeground(new java.awt.Color(0, 0, 0));
        arrow8.setText("▼");
        arrow8.setBorder(null);
        arrow8.setBorderPainted(false);
        arrow8.setContentAreaFilled(false);
        arrow8.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        jPanel2.add(arrow8, gridBagConstraints);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 140, 150, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdocao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arrow1;
    private javax.swing.JButton arrow2;
    private javax.swing.JButton arrow3;
    private javax.swing.JButton arrow4;
    private javax.swing.JButton arrow5;
    private javax.swing.JButton arrow6;
    private javax.swing.JButton arrow7;
    private javax.swing.JButton arrow8;
    private javax.swing.JButton btAplicar;
    private javax.swing.JLabel cidade;
    private javax.swing.JLabel especie;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel idade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loja;
    private javax.swing.JLabel ong;
    private javax.swing.JLabel porte;
    private javax.swing.JLabel sexo;
    // End of variables declaration//GEN-END:variables
}
